<h3>Import all packages</h3>

In [1]:
import pandas as pd
import numpy as np
import math

<h3> Operations with dataframe </h3>

In [2]:
df = pd.read_csv("Development_IT.csv")
df

id                                              title  \
0       567828  2020 Complete Python Bootcamp: From Zero to He...   
1       625204                         The Web Developer Bootcamp   
2       950390  Machine Learning A-Z™: Hands-On Python & R In ...   
3       756150        Angular - The Complete Guide (2020 Edition)   
4       533682  Java Programming Masterclass for Software Deve...   
...        ...                                                ...   
32746  1516977  Fundamental Service Oriented Arch (SOA) Securi...   
32747  1479824  Linux Certification for Experts - Practice Tes...   
32748  1879598  SAP SuccessFactors Employee Central Payroll Fu...   
32749  1940616                  Comptia Linux+ / LPIC-1 (102-400)   
32750   543712                    Cisco Networking CCNA IPv6 OSPF   

                                                     url  is_paid  \
0                      /course/complete-python-bootcamp/     True   
1                    /course/the-web-developer-bootcamp/     True   
2                               /course/machinelearning/     True   
3               /course/the-complete-guide-to-angular-2/     True   
4       /course/java-the-complete-java-developer-course/     True   
...                                                  ...      ...   
32746  /course/fundamental-service-oriented-arch-soa-...     True   
32747  /course/linux-certification-for-beginners-prac...     True   
32748       /course/public-transport-management-systems/     True   
32749              /course/comptia-linux-lpic-1-102-400/     True   
32750            /course/networkingstepbystep-ipv6-ospf/     True   

       num_subscribers  avg_rating   rating  num_reviews  \
0              1086954     4.56326  4.56743       314098   
1               592474     4.64777  4.65291       181621   
2               687330     4.55210  4.54932       131007   
3               417746     4.57687  4.58594       128705   
4               497195     4.56571  4.57203       122306   
...                ...         ...      ...          ...   
32746               16     3.25000  2.65702            2   
32747               15     4.00000  3.56818            2   
32748               19     2.75000  2.70354            2   
32749             1082     3.75000  3.72059            2   
32750              858     4.50000  4.48220            2   

       num_published_lectures  num_published_practice_tests  \
0                         152                             0   
1                         405                             0   
2                         323                             0   
3                         455                             0   
4                         400                             0   
...                       ...                           ...   
32746                       0                             2   
32747                       0                             2   
32748                       5                             0   
32749                      31                             0   
32750                      24                             0   

                    created        published_time  discount_price__amount  \
0      2015-07-29T00:12:23Z  2015-10-12T21:42:53Z                   455.0   
1      2015-09-28T21:32:19Z  2015-11-02T21:13:27Z                   455.0   
2      2016-09-05T09:54:22Z  2016-09-13T21:43:44Z                   455.0   
3      2016-02-08T17:02:55Z  2016-02-11T07:29:29Z                   462.0   
4      2015-06-21T20:25:56Z  2015-07-21T22:01:13Z                   455.0   
...                     ...                   ...                     ...   
32746  2018-01-19T09:03:46Z  2018-01-28T09:20:37Z                   455.0   
32747  2017-12-23T12:44:39Z  2017-12-24T07:38:36Z                   455.0   
32748  2018-08-27T14:43:42Z  2018-09-19T23:19:18Z                  1280.0   
32749  2018-09-30T15:11:27Z  2018-12-11T16:22:32Z                   455.0   
32750  2015-07-03T02:24:30Z  

In [3]:
#Check for null values
df.isnull().values.any() #False - implies no NULL values

False

In [4]:
#Check for duplicates if any
l=[]
for i,j in enumerate(df['id'].value_counts()):
    if j==2:
        l.append(df['id'].value_counts().index[i])
print(l)#Implies duplicates are removed

[]


In [5]:
#We need to apply a neural network which is a non linear model.
#We have many steps to do the following thing.
#Firstly identiy all columns used for identifying target variable.
print(df.columns)

Index(['id', 'title', 'url', 'is_paid', 'num_subscribers', 'avg_rating',
       'rating', 'num_reviews', 'num_published_lectures',
       'num_published_practice_tests', 'created', 'published_time',
       'discount_price__amount', 'price_detail__amount'],
      dtype='object')


In [6]:
#Select few columns(features) for Neural network - num_subscribers, avg_rating, rating, num_reviews, num_published_lectures, num_published_practice tests, discount_price__amount.
#Target feature would be price_detail__amount

<h3> Import all packages </h3>

In [7]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score

Using TensorFlow backend.


<h3> Consider the required sample for training and testing Neural Network </h3>

In [8]:
df_sample = df.sample(frac=0.15, axis=0)
df_sample

id                                              title  \
26688  2311894              SCCM Administration - Be an 'Expert'!   
26988    63060  Become TOGAF Certified with exam preparation f...   
30063  2565064  Java SE11 Programmer 1 (1Z0-815) - Practice Tests   
7345   1661674  C# basics in 70 minutes for beginners: Learn C...   
1295     14346           Learn C# Programming (In Ten Easy Steps)   
...        ...                                                ...   
15432  1074796                  Learn Business Negotiation Skills   
27659  1128926  Wordpress Security Master Class Protect Your B...   
15997   994242  Jesus Teaches YOU How to Build a WorldClass Bu...   
14682  1606940      Sourcing From China | Crowdfunding Case Study   
4486    834924                           How to create HTML Forms   

                                                     url  is_paid  \
26688                /course/sccm-administration-expert/     True   
26988            /course/togaf-exam-preparation-level-2/     True   
30063  /course/java-se11-programmer-1-1z0-815-practic...     True   
7345                 /course/learn-c-sharp-fundamentals/     True   
1295   /course/learn-c-sharp-programming-in-ten-easy-...     True   
...                                                  ...      ...   
15432         /course/learn-business-negotiation-skills/     True   
27659  /course/wordpress-security-master-class-protec...     True   
15997  /course/the-jesus-secret-how-to-build-a-world-...     True   
14682  /course/sourcing-from-china-crowdfunding-case-...     True   
4486                   /course/how-to-create-html-forms/     True   

       num_subscribers  avg_rating   rating  num_reviews  \
26688              438     4.36364  4.35555           66   
26988              928     3.95000  4.00476           56   
30063              168     4.20000  4.20121           12   
7345              4642     3.65000  3.11321           23   
1295              3994     4.32292  4.27152          528   
...                ...         ...      ...          ...   
15432              974     4.50000  4.38601           23   
27659             5096     4.60000  4.32932           39   
15997              981     4.90000  4.89161           18   
14682             3669     3.90000  3.75780           32   
4486              3816     3.75000  3.65281           74   

       num_published_lectures  num_published_practice_tests  \
26688                      55                             0   
26988                      19                             0   
30063                       0                             5   
7345                       19                             0   
1295                      126                             0   
...                       ...                           ...   
15432                       7                             0   
27659                      42                             0   
15997                       7                             0   
14682                      12                             0   
4486                        8                             0   

                    created        published_time  discount_price__amount  \
26688  2019-04-08T06:06:14Z  2019-04-18T12:18:26Z                   455.0   
26988  2013-06-30T13:31:25Z  2013-07-07T21:58:54Z                  1280.0   
30063  2019-09-18T04:49:09Z  2019-09-24T09:03:06Z                   455.0   
7345   2018-04-24T20:32:02Z  2018-04-29T21:31:43Z                   455.0   
1295   2012-02-22T18:11:03Z  2012-03-26T15:30:40Z                   481.0   
...                     ...                   ...                     ...   
15432  2017-01-13T13:36:01Z  2017-01-16T23:37:13Z                   455.0   
27659  2017-02-27T14:55:27Z  2017-03-24T19:13:26Z                   455.0   
15997  2016-10-25T17:25:56Z  2016-10-26T15:03:03Z                   455.0   
14682  2018-03-20T07:00:33Z  2018-03-28T21:15:30Z                   455.0   
4486   2016-04-29T00:54:50Z  

In [9]:
#Consider required columns for input feature and target variable
X = df_sample[['num_subscribers', 'num_reviews', 'num_published_lectures']].values
Y = df_sample[['avg_rating']].values

In [10]:
#Define the model
seed = 10
np.random.seed(seed)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
for train, test in kfold.split(X, Y):
    model = Sequential()
    #Add layers in the model
    model.add(Dense(128, input_dim=3, activation='relu'))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    #Compiler model
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
    model.fit(X[train], Y[train], epochs=35, verbose=1)







Epoch 1/35
4421/4421 [==============================] - 1s 283us/step - loss: 249518.9341 - mean_absolute_error: 66.6962
Epoch 2/35
4421/4421 [==============================] - 0s 57us/step - loss: 80961.7664 - mean_absolute_error: 58.7053
Epoch 3/35
4421/4421 [==============================] - 0s 61us/step - loss: 41677.6038 - mean_absolute_error: 45.7273
Epoch 4/35
4421/4421 [==============================] - 0s 54us/step - loss: 114375.2310 - mean_absolute_error: 34.5554
Epoch 5/35
4421/4421 [==============================] - 0s 51us/step - loss: 204840.0481 - mean_absolute_error: 33.8708
Epoch 6/35
4421/4421 [==============================] - 0s 54us/step - loss: 19467.0155 - mean_absolute_error: 28.3489
Epoch 7/35
4421/4421 [==============================] - 0s 60us/step - loss: 13370.3075 - mean_absolute_error: 26.6632
Epoch 8/35
4421/4421 [==============================] - 0s 50us/step - loss: 8357.0384 - mean_absolute_error: 18.5755
Epoch 9/35
4421/4421 [=================

4422/4422 [==============================] - 0s 52us/step - loss: 4511.0626 - mean_absolute_error: 6.7135
Epoch 24/35
4422/4422 [==============================] - 0s 52us/step - loss: 1316.3223 - mean_absolute_error: 7.4480
Epoch 25/35
4422/4422 [==============================] - 0s 49us/step - loss: 1811.3972 - mean_absolute_error: 8.0937
Epoch 26/35
4422/4422 [==============================] - 0s 49us/step - loss: 699.3772 - mean_absolute_error: 5.9133
Epoch 27/35
4422/4422 [==============================] - 0s 49us/step - loss: 459.7636 - mean_absolute_error: 4.7103
Epoch 28/35
4422/4422 [==============================] - 0s 51us/step - loss: 154.9313 - mean_absolute_error: 3.0441
Epoch 29/35
4422/4422 [==============================] - 0s 48us/step - loss: 123.2187 - mean_absolute_error: 1.9950
Epoch 30/35
4422/4422 [==============================] - 0s 46us/step - loss: 2.8778 - mean_absolute_error: 0.7254
Epoch 31/35
4422/4422 [==============================] - 0s 47us/step - los

4422/4422 [==============================] - 0s 62us/step - loss: 17481.7038 - mean_absolute_error: 18.1030
Epoch 20/35
4422/4422 [==============================] - 0s 60us/step - loss: 9821.0781 - mean_absolute_error: 17.9875
Epoch 21/35
4422/4422 [==============================] - 0s 62us/step - loss: 12607.1507 - mean_absolute_error: 23.7575
Epoch 22/35
4422/4422 [==============================] - 0s 57us/step - loss: 18322.3190 - mean_absolute_error: 15.7226
Epoch 23/35
4422/4422 [==============================] - 0s 57us/step - loss: 11124.9047 - mean_absolute_error: 18.5282
Epoch 24/35
4422/4422 [==============================] - 0s 57us/step - loss: 5607.2108 - mean_absolute_error: 11.8142
Epoch 25/35
4422/4422 [==============================] - 0s 51us/step - loss: 3929.3363 - mean_absolute_error: 9.2287
Epoch 26/35
4422/4422 [==============================] - 0s 50us/step - loss: 10889.0692 - mean_absolute_error: 16.0156
Epoch 27/35
4422/4422 [==============================] -

In [11]:
#Evaluate model on test
mse_value, mae_value = model.evaluate(X[test], Y[test], verbose=0)
print(mse_value)
print(mae_value)

0.3422680450432655
0.42867715520188665


In [12]:
#Prediction and check r^2 value
y_pred = model.predict(X[test])
r2_score(Y[test], y_pred)

0.5694301074350108

In [13]:
#Print the predicted and true value.
y_pred = model.predict(X[test])
print(y_pred, Y)

[[ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.2464437 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.037402  ]
 [ 4.0969057 ]
 [ 3.9459543 ]
 [ 4.0969057 ]
 [ 3.9766402 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0995984 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.18602   ]
 [ 4.114999  ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.3580866 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 0.43867898]
 [ 4.0969057 ]
 [ 0.6712196 ]
 [ 4.436103  ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 0.09192109]
 [ 4.0969057 ]
 [ 4.2175856 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.130432  ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.181238  ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 2.0776255 ]
 [ 4.157687  ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.7093143 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.0969057 ]
 [ 4.09690

<h3> This part completes a Neural network for predicting continuous variable. </h3>

<h1> Neral Network for predicting multiclass classification problem </h1>

<h3> Import all the packages </h3>

In [147]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, classification_report, f1_score

<h3> Consider a sample for performing the classification problem </h3>

In [148]:
df_sample = df.sample(frac=0.15, axis=0)
df_sample

id                                              title  \
4520    641236  Basic JavaScript: Build 4 Basic JavaScript Pro...   
18540  3373686  Sales Mastery: Rapid B2B Sales Growth & Epic C...   
25219  1672148                 CNC Lathe programming using G Code   
27837  2883952  Declarations and Initializations for C Program...   
20724  3427566  Financial Management for Entrepreneurs and Fre...   
...        ...                                                ...   
1612   1051008                MongoDB 3.2: Professional Developer   
1321    942454  The Complete iOS Development Course. Swift Pro...   
26451  2263606  Physical Access Hacking Windows Xp, 7, 8, 10, ...   
2518   1227924  Implementing a Data Warehouse with Microsoft S...   
6307    497648  Build a Cordova Chat APP using Strophe and eJa...   

                                                     url  is_paid  \
4520     /course/practical-javascript-javascript-basics/     True   
18540  /course/sales-mastery-rapid-b2b-sales-growth-e...     True   
25219        /course/cnc-lathe-programming-using-g-code/     True   
27837  /course/declarations-and-initializations-for-c...     True   
20724  /course/finances-and-budgeting-for-entrepreneu...     True   
...                                                  ...      ...   
1612             /course/mongodb-professional-developer/     True   
1321   /course/learn-full-swift-course-xcode-ios-prog...     True   
26451                     /course/physicalaccesshacking/     True   
2518   /course/implementing-a-data-warehouse-with-mic...     True   
6307   /course/create-a-cross-platform-chat-app-using...     True   

       num_subscribers  avg_rating   rating  num_reviews  \
4520               825     4.35000  4.24073           73   
18540                9     5.00000  5.00000            5   
25219             1231     4.17949  4.20768          194   
27837             5616     3.85000  3.90397           36   
20724              650     5.00000  5.00000            2   
...                ...         ...      ...          ...   
1612              2539     4.56250  4.75055          398   
1321              3025     4.60000  4.64769          517   
26451            14096     3.25000  3.02094           76   
2518              1896     3.97222  3.97406          205   
6307               225     2.65000  2.37468           35   

       num_published_lectures  num_published_practice_tests  \
4520                       37                             0   
18540                      83                             0   
25219                      17                             0   
27837                       0                             6   
20724                      25                             0   
...                       ...                           ...   
1612                      132                             0   
1321                      329                             0   
26451                      68                             0   
2518                       70                             0   
6307                       27                             0   

                    created        published_time  discount_price__amount  \
4520   2015-10-15T09:58:21Z  2016-02-04T03:55:24Z                   455.0   
18540  2020-07-28T18:15:43Z  2020-09-01T23:53:55Z                   455.0   
25219  2018-05-02T07:39:04Z  2018-05-07T17:54:49Z                   455.0   
27837  2020-03-18T20:05:00Z  2020-03-19T17:15:34Z                   455.0   
20724  2020-08-17T19:14:39Z  2020-08-24T11:26:13Z                  1600.0   
...                     ...                   ...                     ...   
1612   2016-12-25T13:51:41Z  2017-01-24T21:59:57Z                   455.0   
1321   2016-08-27T04:18:03Z  2016-09-09T21:37:21Z                   468.0   
26451  2019-03-10T00:43:45Z  2019-03-21T17:17:26Z                   455.0   
2518   2017-05-24T13:24:19Z  2017-05-27T05:56:16Z                   455.0   
6307   2015-05-09T15:46:38Z  

In [149]:
#Identify the in[put features and corresponding target vriable.
X = df_sample[['rating', 'num_reviews', 'num_published_lectures']].values
Y = df_sample[['num_published_practice_tests']].values

In [150]:
#Encodeing done as target variable is a categorical one.
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
#One hot encoding
Y = np_utils.to_categorical(encoded_Y)
print(Y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


e:\anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [151]:
#Define the classification model
seed = 20
np.random.seed(seed)
kfold = KFold(n_splits=5, shuffle=True, random_state=seed)
for train, test in kfold.split(X, Y):
    model = Sequential()
    #Add layers in the model
    model.add(Dense(24, input_dim=3, activation='relu'))
    model.add(Dense(8, activation='relu'))
    model.add(Dense(7, activation='softmax'))
    #Compiler model
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(X[train], Y[train], epochs=10, verbose=1)

Epoch 1/10
3930/3930 [==============================] - 12s 3ms/step - loss: 2.8039 - acc: 0.5265
Epoch 2/10
3930/3930 [==============================] - 1s 238us/step - loss: 1.6701 - acc: 0.9168
Epoch 3/10
3930/3930 [==============================] - 1s 223us/step - loss: 1.5036 - acc: 0.9308
Epoch 4/10
3930/3930 [==============================] - 1s 222us/step - loss: 1.3463 - acc: 0.9305
Epoch 5/10
3930/3930 [==============================] - 1s 254us/step - loss: 1.2032 - acc: 0.9321
Epoch 6/10
3930/3930 [==============================] - 1s 231us/step - loss: 1.0755 - acc: 0.9323
Epoch 7/10
3930/3930 [==============================] - 1s 246us/step - loss: 0.9626 - acc: 0.9328
Epoch 8/10
3930/3930 [==============================] - 1s 228us/step - loss: 0.8656 - acc: 0.9328
Epoch 9/10
3930/3930 [==============================] - 1s 240us/step - loss: 0.7774 - acc: 0.9341
Epoch 10/10
3930/3930 [==============================] - 1s 224us/step - loss: 0.7159 - acc: 0.9321
Epoch 1/10

In [152]:
#Evaluate model on test
loss, accuracy = model.evaluate(X[test], Y[test], verbose=0)
print("Loss: ", loss)
print("Accuracy: ", accuracy)

Loss:  0.4820562945849541
Accuracy:  0.9134419548292996


In [153]:
#Predict and compare with true values
y_pred = model.predict(X[test])
Y_prediction = y_pred.argmax(1)
Y_test = Y[test].argmax(1)
print(Y_prediction, Y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [154]:
#Confusion matrix and other metrics:
print(confusion_matrix(Y_test, Y_prediction))

[[897   0   0   0   0   0   0]
 [ 18   0   0   0   0   0   0]
 [ 26   0   0   0   0   0   0]
 [  9   0   0   0   0   0   0]
 [ 11   0   0   0   0   0   0]
 [  9   0   0   0   0   0   0]
 [ 12   0   0   0   0   0   0]]


In [155]:
#All the metrics and evaluation results.
print('Accuracy:', accuracy_score(Y_test, Y_prediction))
print('F1 score:', f1_score(Y_test, Y_prediction, average='weighted'))
print('Recall:', recall_score(Y_test, Y_prediction, average='weighted'))
print('Precision:', precision_score(Y_test, Y_prediction, average='weighted'))
print('\n clasification report:\n', classification_report(Y_test, Y_prediction))
print('\n confussion matrix:\n',confusion_matrix(Y_test, Y_prediction))

Accuracy: 0.9134419551934827
F1 score: 0.8721207384870185
Recall: 0.9134419551934827
Precision: 0.8343762055076924

 clasification report:
               precision    recall  f1-score   support

           0       0.91      1.00      0.95       897
           1       0.00      0.00      0.00        18
           2       0.00      0.00      0.00        26
           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00         9
           6       0.00      0.00      0.00        12

    accuracy                           0.91       982
   macro avg       0.13      0.14      0.14       982
weighted avg       0.83      0.91      0.87       982


 confussion matrix:
 [[897   0   0   0   0   0   0]
 [ 18   0   0   0   0   0   0]
 [ 26   0   0   0   0   0   0]
 [  9   0   0   0   0   0   0]
 [ 11   0   0   0   0   0   0]
 [  9   0   0   0   0   0   0]
 [ 12   0   0   0   0   0   0]]


e:\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
